use lazy_static::lazy_static;
use std::vec::Vec;

/// A basic structure of data defining an instruction supported by the CPU. Each instruction is
/// submitted to the CPU via a single byte which determines the functionality of the instruction
/// in how it loads its data from memory (if any) and how it operates on that data.
/// 
/// There are 56 different operations and 12 different addressing modes. Not all operations support
/// all addressing modes. The input format for the instruction opcode (a byte) allows for 256 total
/// combinations, many of which are unused.
/// 
/// For reference: http://www.obelisk.me.uk/6502/reference.html
pub struct Instruction<'a> {
	// The name of the instruction (3 alphabetic characters, all upper-case)
	name: &'a str,
	// The number of cycles required for computing this instruction
	cycles: u8,
	// A pointer to the function which implements the Operation logic for this instruction 
	// operate_function: Option<u8>,
	// A pointer to the function which implements the Addressing Mode logic for this instruction
	// address_mode_function: Option<u8>,
}

/// The set of flags which are used to compose the status code bitmask on the CPU.
/// The status code bitmask is updated after every instruction, and thus the bitmask can be used
/// to inform future instructions about prior results, or to control various aspects of functionality,
/// e.g., if the I flag is set (disable interrupts), then IRQ signals can be ignored (but NMI cannot).
pub enum StatusFlag {
    C = 1 << 0, // Carry Bit
    Z = 1 << 1, // Zero
    I = 1 << 2, // Disable Interrupts
    D = 1 << 3, // Decimal Mode (unused)
    B = 1 << 4, // Break
    U = 1 << 5, // Unused
    V = 1 << 6, // Overflow
    N = 1 << 7, // Negative
}

lazy_static! {
	/// A reference table of instructions by their byte-length opcode. There are 256 of these.
	/// 
	/// Reference: http://archive.6502.org/datasheets/rockwell_r650x_r651x.pdf
	static ref INSTRUCTION_LOOKUP: Vec<Instruction<'static>> = vec![
		Instruction { name: "BRK", cycles: 7 },
		Instruction { name: "ORA", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 3 },
		Instruction { name: "ORA", cycles: 3 },
		Instruction { name: "ASL", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "PHP", cycles: 3 },
		Instruction { name: "ORA", cycles: 2 },
		Instruction { name: "ASL", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "ORA", cycles: 4 },
		Instruction { name: "ASL", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "BPL", cycles: 2 },
		Instruction { name: "ORA", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "ORA", cycles: 4 },
		Instruction { name: "ASL", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "CLC", cycles: 2 },
		Instruction { name: "ORA", cycles: 4 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "ORA", cycles: 4 },
		Instruction { name: "ASL", cycles: 7 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "JSR", cycles: 6 },
		Instruction { name: "AND", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "BIT", cycles: 3 },
		Instruction { name: "AND", cycles: 3 },
		Instruction { name: "ROL", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "PLP", cycles: 4 },
		Instruction { name: "AND", cycles: 2 },
		Instruction { name: "ROL", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "BIT", cycles: 4 },
		Instruction { name: "AND", cycles: 4 },
		Instruction { name: "ROL", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "BMI", cycles: 2 },
		Instruction { name: "AND", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "AND", cycles: 4 },
		Instruction { name: "ROL", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "SEC", cycles: 2 },
		Instruction { name: "AND", cycles: 4 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "AND", cycles: 4 },
		Instruction { name: "ROL", cycles: 7 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "RTI", cycles: 6 },
		Instruction { name: "EOR", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 3 },
		Instruction { name: "EOR", cycles: 3 },
		Instruction { name: "LSR", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "PHA", cycles: 3 },
		Instruction { name: "EOR", cycles: 2 },
		Instruction { name: "LSR", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "JMP", cycles: 3 },
		Instruction { name: "EOR", cycles: 4 },
		Instruction { name: "LSR", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "BVC", cycles: 2 },
		Instruction { name: "EOR", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "EOR", cycles: 4 },
		Instruction { name: "LSR", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "CLI", cycles: 2 },
		Instruction { name: "EOR", cycles: 4 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "EOR", cycles: 4 },
		Instruction { name: "LSR", cycles: 7 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "RTS", cycles: 6 },
		Instruction { name: "ADC", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 3 },
		Instruction { name: "ADC", cycles: 3 },
		Instruction { name: "ROR", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "PLA", cycles: 4 },
		Instruction { name: "ADC", cycles: 2 },
		Instruction { name: "ROR", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "JMP", cycles: 5 },
		Instruction { name: "ADC", cycles: 4 },
		Instruction { name: "ROR", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "BVS", cycles: 2 },
		Instruction { name: "ADC", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "ADC", cycles: 4 },
		Instruction { name: "ROR", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "SEI", cycles: 2 },
		Instruction { name: "ADC", cycles: 4 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "ADC", cycles: 4 },
		Instruction { name: "ROR", cycles: 7 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "STA", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "STY", cycles: 3 },
		Instruction { name: "STA", cycles: 3 },
		Instruction { name: "STX", cycles: 3 },
		Instruction { name: "XXX", cycles: 3 },
		Instruction { name: "DEY", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "TXA", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "STY", cycles: 4 },
		Instruction { name: "STA", cycles: 4 },
		Instruction { name: "STX", cycles: 4 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "BCC", cycles: 2 },
		Instruction { name: "STA", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "STY", cycles: 4 },
		Instruction { name: "STA", cycles: 4 },
		Instruction { name: "STX", cycles: 4 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "TYA", cycles: 2 },
		Instruction { name: "STA", cycles: 5 },
		Instruction { name: "TXS", cycles: 2 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "STA", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "LDY", cycles: 2 },
		Instruction { name: "LDA", cycles: 6 },
		Instruction { name: "LDX", cycles: 2 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "LDY", cycles: 3 },
		Instruction { name: "LDA", cycles: 3 },
		Instruction { name: "LDX", cycles: 3 },
		Instruction { name: "XXX", cycles: 3 },
		Instruction { name: "TAY", cycles: 2 },
		Instruction { name: "LDA", cycles: 2 },
		Instruction { name: "TAX", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "LDY", cycles: 4 },
		Instruction { name: "LDA", cycles: 4 },
		Instruction { name: "LDX", cycles: 4 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "BCS", cycles: 2 },
		Instruction { name: "LDA", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "LDY", cycles: 4 },
		Instruction { name: "LDA", cycles: 4 },
		Instruction { name: "LDX", cycles: 4 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "CLV", cycles: 2 },
		Instruction { name: "LDA", cycles: 4 },
		Instruction { name: "TSX", cycles: 2 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "LDY", cycles: 4 },
		Instruction { name: "LDA", cycles: 4 },
		Instruction { name: "LDX", cycles: 4 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "CPY", cycles: 2 },
		Instruction { name: "CMP", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "CPY", cycles: 3 },
		Instruction { name: "CMP", cycles: 3 },
		Instruction { name: "DEC", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "INY", cycles: 2 },
		Instruction { name: "CMP", cycles: 2 },
		Instruction { name: "DEX", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "CPY", cycles: 4 },
		Instruction { name: "CMP", cycles: 4 },
		Instruction { name: "DEC", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "BNE", cycles: 2 },
		Instruction { name: "CMP", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "CMP", cycles: 4 },
		Instruction { name: "DEC", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "CLD", cycles: 2 },
		Instruction { name: "CMP", cycles: 4 },
		Instruction { name: "NOP", cycles: 2 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "CMP", cycles: 4 },
		Instruction { name: "DEC", cycles: 7 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "CPX", cycles: 2 },
		Instruction { name: "SBC", cycles: 6 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "CPX", cycles: 3 },
		Instruction { name: "SBC", cycles: 3 },
		Instruction { name: "INC", cycles: 5 },
		Instruction { name: "XXX", cycles: 5 },
		Instruction { name: "INX", cycles: 2 },
		Instruction { name: "SBC", cycles: 2 },
		Instruction { name: "NOP", cycles: 2 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "CPX", cycles: 4 },
		Instruction { name: "SBC", cycles: 4 },
		Instruction { name: "INC", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "BEQ", cycles: 2 },
		Instruction { name: "SBC", cycles: 5 },
		Instruction { name: "XXX", cycles: 2 },
		Instruction { name: "XXX", cycles: 8 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "SBC", cycles: 4 },
		Instruction { name: "INC", cycles: 6 },
		Instruction { name: "XXX", cycles: 6 },
		Instruction { name: "SED", cycles: 2 },
		Instruction { name: "SBC", cycles: 4 },
		Instruction { name: "NOP", cycles: 2 },
		Instruction { name: "XXX", cycles: 7 },
		Instruction { name: "XXX", cycles: 4 },
		Instruction { name: "SBC", cycles: 4 },
		Instruction { name: "INC", cycles: 7 },
		Instruction { name: "XXX", cycles: 7 },
	];
}
